---
- name: Initialize the cluster
  ansible.builtin.shell: "kubeadm init --pod-network-cidr {{ k8s_pod_cidr }} --kubernetes-version {{ k8s_version }}"
  register: kubeadm_output

- name: Print kubeadm init output
  debug:
    var: kubeadm_output.stdout_lines

- name: Get kubeconfig file
  ansible.builtin.shell: "mkdir -p $HOME/.kube &&  cp -i /etc/kubernetes/admin.conf $HOME/.kube/config &&  chown $(id -u):$(id -g) $HOME/.kube/config"
  environment:
    HOME: "/root"

- name: Install Calico network plugin
  ansible.builtin.shell: "kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/calico.yaml"
  environment:
    HOME: "/root"

- name: Create Join token for the worker nodes to join the cluster
  ansible.builtin.shell: "kubeadm token create --print-join-command"
  register: join_command

- name: "Add K8S Token to dummy host"
  add_host:
    name:   "K8S_TOKEN_HOLDER"
    token:  "{{ join_command.stdout }}"